name: Push Request Testing

on: [push]

jobs:
  test:
    name: Test on ${{ matrix.os }}, Python ${{ matrix.python-version}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
        python-version: [3.7, 3.8, 3.9]

  steps:
  - uses: actions/checkout@v1

  - uses: conda-incubator/setup-miniconda@v2
    with:
      python-version: ${{ matrix.python-version }}
      environment-file: devtools/conda-envs/test_env.yaml
      
      channels: conda-forge,defaults
      
      activate-environment: test
      auto-update-conda: false
      auto-activate-base: false
      show-channel-urls: false
      
  - name: Install package
    shell: bash -l {0}
    run: |
      python -m pip install . --no-deps
      make all
#      python finish_up.py
      conda list
      
  - name: Run Tests
    shell: bash -l {0}
    run: |
      pytest -v --cov=connormath --cov-report=xml --color=yes connormath/tests

  - name: CodeCov
    uses: codecov/codecov-action@v1
    with:
      file: ./coverage.xml
      flags: unittests
      name: codecov-${{ matrix.os }}-py${{ matrix.python-version }}
